In [5]:
import numpy as np
file =open("input3.txt","r")
file=file.read().split()

s=file[0]
s2=file[1]
s3=file[2]
def LCS(X,Y,Z):
    m=len(X)+1
    n=len(Y)+1
    o=len(Z)+1
    c=np.zeros((m,n,o))
    for i in range(1,m):
        for j in range(1,n):
            for k in range(1,o):
                if X[i-1]==Y[j-1] and X[i-1]==Z[k-1]:
                    c[i][j][k]=1+(c[i-1][j-1][k-1])
                else:
                    maxim=max(c[i-1][j][k],c[i][j-1][k])
                    maxim=max(maxim,c[i][j][k-1])
                    c[i][j][k]=maxim
    return c
res=LCS(s,s2,s3)
file=open("output3.txt","w")
file.write(str(int(res[-1][-1][-1])))
file.close()
print(res)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 1. 1.]
  [0. 0. 1. 1. 1. 1.]
  [0. 0. 1. 1. 1. 1.]
  [0. 0. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 1. 1.]
  [0. 0. 1. 2. 2. 2.]
  [0. 0. 1. 2. 2. 2.]
  [0. 0. 1. 2. 2. 2.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 1. 1. 1.]
  [0. 0. 1. 2. 2. 2.]
  [0. 0. 1. 2. 3. 3.]
  [0. 0. 1. 2. 3. 3.]]]
